<?php

use app\migrations\Migration;

class m170202_075518_add_new_data_on_service_table extends Migration
{
    public function safeUp()
    {
        $this->insert('{{%service}}',['id'=>'1','name'=>'Web Design','icon'=>'web','slug'=>'web-design','description'=>'Wake up business and your business identity on the Internet through the Website','metakey'=>'Web Design, Web Development of ATC, Web Developer, Consultations','metadesc'=>'Wake up business and your business identity on the Internet through the Website','status'=>'1','created_at'=>'2017-02-02 14:35:12','updated_at'=>'2017-02-16 10:51:17','created_by'=>'1','updated_by'=>'1']);
        $this->insert('{{%service}}',['id'=>'2','name'=>'Custom Web','icon'=>'web','slug'=>'custom-web','description'=>'Web application development is exciting and dynamic. Take into account usability.','metakey'=>'Custom Web, Wordpress, Joomla','metadesc'=>'Web application development is exciting and dynamic. Take into account usability.','status'=>'1','created_at'=>'2017-02-02 14:37:51','updated_at'=>'2017-02-16 10:52:17','created_by'=>'1','updated_by'=>'1']);
        $this->insert('{{%service}}',['id'=>'3','name'=>'Software and Programming','icon'=>'web_asset','slug'=>'software-and-programming','description'=>'Improve the performance of companies with the Software in accordance with Business Process you.','metakey'=>'Software and programming, based on Visual Basic .NET','metadesc'=>'Improve the performance of companies with the Software in accordance with Business Process you.','status'=>'1','created_at'=>'2017-02-02 14:38:32','updated_at'=>'2017-02-16 10:53:19','created_by'=>'1','updated_by'=>'1']);
        $this->insert('{{%service}}',['id'=>'4','name'=>'Maintenance and Renovation','icon'=>'web_asset','slug'=>'maintenance-and-renovation','description'=>'for the existing website or network. For convenience, data security, and effectiveness.','metakey'=>'Software and Website maintenance or renovation','metadesc'=>'Maintenance and renovation the existing website or network. For convenience, data security, and effectiveness.','status'=>'1','created_at'=>'2017-02-02 14:39:05','updated_at'=>'2017-02-16 10:56:47','created_by'=>'1','updated_by'=>'1']);
        $this->insert('{{%service}}',['id'=>'5','name'=>'Hardware and Networking','icon'=>'network_wifi','slug'=>'hardware-and-networking','description'=>'Hardware and Network Infrastructure that will either provide comfort in work.','metakey'=>'hardware, networking, network based on linux ubuntu, network based on linux CentOS, Miktorik','metadesc'=>'Hardware and Network Infrastructure that will either provide comfort in work.','status'=>'1','created_at'=>'2017-02-02 14:39:39','updated_at'=>'2017-02-16 10:57:56','created_by'=>'1','updated_by'=>'1']);
        $this->insert('{{%service}}',['id'=>'6','name'=>'Training','icon'=>'grade','slug'=>'training','description'=>'Knowledge in your hand, Future Technolgy and Expert experience','metakey'=>'Training Ionic, Web-based, CodeIgniter, Yii and Laravel Framework, CentOS and Mikrotik','metadesc'=>'Knowledge in your hand, Future Technolgy and Expert experience. Training Ionic, Web-based, CodeIgniter, Yii and Laravel Framework, CentOS and Mikrotik','status'=>'1','created_at'=>'2017-02-02 14:40:03','updated_at'=>'2017-02-16 10:58:59','created_by'=>'1','updated_by'=>'1']);
        $this->insert('{{%service}}',['id'=>'7','name'=>'Project Management','icon'=>'web','slug'=>'project-management','description'=>'Valuations, Strategic advice, Cost modelling & estimation, Financial evaluation, Feasibility studies, Risk analysis, Reporting.','metakey'=>'Valuations, Strategic advice, Cost modelling & estimation, Financial evaluation, Feasibility studies','metadesc'=>'Valuations, Strategic advice, Cost modelling & estimation, Financial evaluation, Feasibility studies, Risk analysis, Reporting.','status'=>'1','created_at'=>'2017-02-16 10:59:44','updated_at'=>'','created_by'=>'1','updated_by'=>'1']);
        $this->insert('{{%service}}',['id'=>'8','name'=>'IT Audit','icon'=>'subject','slug'=>'it-audit','description'=>'Evaluation system, performance, Risk analysis, Reporting and infrastructure to support information technology systems','metakey'=>'Evaluation system, performance, Risk analysis, Reporting and infrastructure to support information t','metadesc'=>'Evaluation system, performance, Risk analysis, Reporting and infrastructure to support information technology systems','status'=>'1','created_at'=>'2017-02-16 11:00:37','updated_at'=>'2017-02-16 11:02:15','created_by'=>'1','updated_by'=>'1']);
$this->insert('{{%service}}',['id'=>'9','name'=>'SEO Service and Friendly','icon'=>'star','slug'=>'seo-service-and-friendly','description'=>'Search Engine Page Rank will give you a better chance than the competitors, Consultation on the needs of your IT','metakey'=>'SEO Friendly Services from ATC','metadesc'=>'Search Engine Page Rank will give you a better chance than the competitors, Consultation on the needs of your IT and know our other services we provid','status'=>'1','created_at'=>'2017-02-16 11:01:31','updated_at'=>'2017-02-16 11:02:46','created_by'=>'1','updated_by'=>'1']);
    }

    public function safeDown()
    {
        $this->truncateTable('{{%service}}');
    }
}
